import { ClueItem, Landmark } from '../types';

export const INITIAL_LANDMARKS: Landmark[] = [
  {
    id: 'trailhead',
    name: 'Peralta Trailhead Camp',
    shortDesc: 'Base camp with fresh water barrel, pack saddle, and trail register.',
    position: { x: -120, y: 0, z: -120 },
    radius: 18,
    clueId: 'clue_trailhead',
    discovered: false,
    type: 'camp',
  },
  {
    id: 'hieroglyphic_spring',
    name: 'Hieroglyphic Oasis & Spring',
    shortDesc: 'A desert canyon pool fed by spring water surrounded by ancient basalt petroglyphs.',
    position: { x: -70, y: 0, z: -20 },
    radius: 16,
    clueId: 'clue_petroglyph',
    discovered: false,
    type: 'spring',
  },
  {
    id: 'massacre_grounds',
    name: '1848 Peralta Massacre Grounds',
    shortDesc: 'Historic battleground marked with weathered ironwood crosses and buried Mexican silver.',
    position: { x: -40, y: 0, z: 90 },
    radius: 20,
    clueId: 'clue_cross',
    discovered: false,
    type: 'massacre',
  },
  {
    id: 'miners_ruins',
    name: "Jacob Waltz's Abandoned Dugout",
    shortDesc: 'Crumbled stone shelter where the German prospector hid his mule pack and pickaxes.',
    position: { x: 30, y: 0, z: -90 },
    radius: 18,
    clueId: 'clue_dugout',
    discovered: false,
    type: 'ruins',
  },
  {
    id: 'weavers_needle',
    name: "Weaver's Needle Lookout",
    shortDesc: 'The 1,000-foot volcanic monolithic spire dominating the Superstition skyline.',
    position: { x: 80, y: 0, z: 15 },
    radius: 25,
    clueId: 'clue_needle',
    discovered: false,
    type: 'needle',
  },
  {
    id: 'eye_ridge',
    name: 'Eye of the Needle Bluff',
    shortDesc: 'A high ridge with a natural aperture in the red dacite rock overlooking a box canyon.',
    position: { x: 130, y: 0, z: -40 },
    radius: 18,
    clueId: 'clue_eye',
    discovered: false,
    type: 'petroglyph',
  },
  {
    id: 'tortilla_flat',
    name: 'Historic Town of Tortilla Flat & Salt River',
    shortDesc: '1880s stagecoach settlement and Roosevelt Dam freight camp situated along the Apache Trail on the south bank of the Salt River Canyon.',
    position: { x: 0, y: 0, z: -252 },
    radius: 40,
    clueId: 'clue_tortilla_flat',
    discovered: true,
    type: 'town',
  },
  {
    id: 'malapais_mountain',
    name: 'Malapais Mountain Summit',
    shortDesc: 'USGS Elev. 4,229 ft. The highest dominant volcanic basalt massif in the northern Superstitions, known as "Black Mountain".',
    position: { x: 95, y: 0, z: -155 },
    radius: 36,
    clueId: 'clue_malapais',
    discovered: false,
    type: 'mountain',
  },
  {
    id: 'pistol_canyon',
    name: 'Pistol Canyon Box Gorge',
    shortDesc: 'Rugged slot canyon below Peters Mesa where Dutch Hunter Roy Bradford lost his revolver in 1920 while seeking the Dutchman cache.',
    position: { x: -46, y: 0, z: -130 },
    radius: 24,
    clueId: 'clue_pistol',
    discovered: false,
    type: 'canyon',
  },
  {
    id: 'lost_dutchman_mine',
    name: 'The Lost Dutchman Mine',
    shortDesc: 'The legendary hidden gold mine masked by ironwood brush and fallen boulders.',
    position: { x: 160, y: 0, z: 110 },
    radius: 15,
    clueId: 'clue_mine',
    discovered: false,
    type: 'mine',
  },
];

export const INITIAL_CLUES: ClueItem[] = [
  {
    id: 'clue_trailhead',
    title: 'Trail Register & Peralta Map Fragment',
    lore: '"From my mine you can see the military road winding through the pass, but from the road you cannot see the mine."',
    hint: 'Head east toward the canyon spring to inspect ancient stone markings.',
    discovered: false,
    landmarkId: 'trailhead',
    iconName: 'Scroll',
    foundAt: 'Peralta Trailhead Camp',
  },
  {
    id: 'clue_petroglyph',
    title: 'Peralta Stone Tablet Symbols',
    lore: '"Follow the stream bed where the water sinks into the sand. Three crosses carved into volcanic tuff mark the trail south."',
    hint: 'Travel south toward the high red bluffs where old wooden crosses stand.',
    discovered: false,
    landmarkId: 'hieroglyphic_spring',
    iconName: 'Sparkles',
    foundAt: 'Hieroglyphic Oasis & Spring',
  },
  {
    id: 'clue_cross',
    title: 'Carved Wooden Cross Inscription',
    lore: '"A silver spur and a rusted stirrup beneath the scree. Jacob Waltz noted: The shadow of the great spire will stretch northeast across the canyon."',
    hint: "Head northeast to Waltz's old stone dugout and prospecting camp.",
    discovered: false,
    landmarkId: 'massacre_grounds',
    iconName: 'Compass',
    foundAt: '1848 Peralta Massacre Grounds',
  },
  {
    id: 'clue_dugout',
    title: "Waltz's Tattered Leather Journal",
    lore: '"Found the mother lode in a narrow cleft. Rose quartz with pure native gold ribboning through the basalt like honey. Masked the entrance with dead mesquite and heavy rocks."',
    hint: "Gaze toward Weaver's Needle. The needle casts a sharp shadow toward the eastern bluffs.",
    discovered: false,
    landmarkId: 'miners_ruins',
    iconName: 'BookOpen',
    foundAt: "Jacob Waltz's Abandoned Dugout",
  },
  {
    id: 'clue_needle',
    title: "Weaver's Needle Shadow Bearings",
    lore: '"At 4 o’clock in the afternoon, the shadow of Weaver\'s Needle points its apex directly at the Eye of the Mountain."',
    hint: 'Climb the ridge northeast to the high bluff with the natural stone window.',
    discovered: false,
    landmarkId: 'weavers_needle',
    iconName: 'Mountain',
    foundAt: "Weaver's Needle Lookout",
  },
  {
    id: 'clue_eye',
    title: 'The Aperture Sightline',
    lore: '"Looking through the natural eye of the rock when the sun sinks low, the golden ray strikes the entrance of the hidden mine shaft across the box canyon."',
    hint: 'Follow the sightline southeast into the secluded box canyon cleft at coords (+160, +110).',
    discovered: false,
    landmarkId: 'eye_ridge',
    iconName: 'Eye',
    foundAt: 'Eye of the Needle Bluff',
  },
  {
    id: 'clue_tortilla_flat',
    title: 'Tortilla Flat Saloon Ledger & Stage Records',
    lore: '"Stagecoach drivers along the Apache Trail recorded Jacob Waltz paying for salt pork, flour, and whiskey with coarse, wire-like gold nuggets that he claimed came from the three red peaks to the south."',
    hint: 'Refill your canteen at the wooden trough, warm up at the town campfire, and trade with the frontier provisioner.',
    discovered: true,
    landmarkId: 'tortilla_flat',
    iconName: 'Building2',
    foundAt: 'Historic Town of Tortilla Flat',
  },
  {
    id: 'clue_malapais',
    title: 'USGS Triangulation Benchmark & Summit Vista',
    lore: '"Malapais Mountain (elev. 4,229 ft) — From this dark basalt caprock, the apex of Weaver\'s Needle aligns true south with the Peralta Trail and the hidden gold-bearing quartz vein."',
    hint: 'Peer south toward Weaver\'s Needle through the surveyor transit, or follow the rocky drainage southwest down into Pistol Canyon.',
    discovered: false,
    landmarkId: 'malapais_mountain',
    iconName: 'Mountain',
    foundAt: 'Malapais Mountain Summit',
  },
  {
    id: 'clue_pistol',
    title: "Roy Bradford's Lost 1870s Colt Revolver & Journal",
    lore: '"Dutch Hunter Roy Bradford lost his Colt single-action revolver in this narrow box gorge while scrambling through boulder pour-offs in 1920. His journal notes: \'The canyon walls narrow to six paces; gold float traces in the gravel wash.\'"',
    hint: 'Follow the winding canyon wash north toward Peters Canyon or scramble up the pack trail west onto Peters Mesa.',
    discovered: false,
    landmarkId: 'pistol_canyon',
    iconName: 'Crosshair',
    foundAt: 'Pistol Canyon Box Gorge',
  },
  {
    id: 'clue_mine',
    title: 'The Lost Dutchman Cache & Shaft',
    lore: '"You have found it! The legendary entrance sealed with ironwood logs and heavy boulders. Beyond lies the vein of crystalline gold Waltz took to Phoenix!"',
    hint: 'Step inside the timbered drift to uncover the lost gold!',
    discovered: false,
    landmarkId: 'lost_dutchman_mine',
    iconName: 'Award',
    foundAt: 'The Lost Dutchman Mine',
  },
];
