import { ClueItem, Landmark } from '../types';

export const INITIAL_LANDMARKS: Landmark[] = [
  {
    id: 'trailhead',
    name: 'Peralta Trailhead Camp',
    shortDesc: 'USGS Elev. 2,420 ft. Southern wilderness portal following the 1840s Sonora mule trail.',
    position: { x: -120, y: 0, z: -120 },
    radius: 18,
    clueId: 'clue_trailhead',
    discovered: false,
    type: 'camp',
    elevationFt: 2420,
    geology: 'Alluvial Fan & South Wilderness Approach Wash',
  },
  {
    id: 'hieroglyphic_spring',
    name: 'Hieroglyphic Oasis & Spring',
    shortDesc: 'USGS Elev. 2,360 ft. Canyon pool fed by perennial bedrock seep, surrounded by ancient Hohokam petroglyphs.',
    position: { x: -70, y: 0, z: -20 },
    radius: 16,
    clueId: 'clue_petroglyph',
    discovered: false,
    type: 'spring',
    elevationFt: 2360,
    geology: 'Basalt Canyon Pool with Prehistoric Hohokam Petroglyphs',
  },
  {
    id: 'massacre_grounds',
    name: '1848 Peralta Massacre Grounds',
    shortDesc: 'USGS Elev. 2,540 ft. Historic Sonoran battleground marked with weathered ironwood crosses.',
    position: { x: -40, y: 0, z: 90 },
    radius: 20,
    clueId: 'clue_cross',
    discovered: false,
    type: 'massacre',
    elevationFt: 2540,
    geology: 'Eroded Rhyolitic Slope & Alluvial Scree',
  },
  {
    id: 'miners_ruins',
    name: "Jacob Waltz's Abandoned Dugout",
    shortDesc: 'USGS Elev. 2,820 ft. Crumbled stone shelter where Waltz hid his mule packs and gold samples.',
    position: { x: 30, y: 0, z: -90 },
    radius: 18,
    clueId: 'clue_dugout',
    discovered: false,
    type: 'ruins',
    elevationFt: 2820,
    geology: 'Dry Canyon Wash & Granite Boulders',
  },
  {
    id: 'weavers_needle',
    name: "Weaver's Needle Lookout",
    shortDesc: 'USGS Elev. 4,553 ft. Arizona\'s 1,000-foot volcanic monolithic dacite plug towering over the Superstitions.',
    position: { x: 80, y: 0, z: 15 },
    radius: 25,
    clueId: 'clue_needle',
    discovered: false,
    type: 'needle',
    elevationFt: 4553,
    geology: 'Eroded Volcanic Dacite Neck / Conduit Plug',
  },
  {
    id: 'eye_ridge',
    name: 'Eye of the Needle Bluff',
    shortDesc: 'USGS Elev. 3,420 ft. Natural rock aperture overlooking Needle Canyon and the eastern box canyons.',
    position: { x: 130, y: 0, z: -40 },
    radius: 18,
    clueId: 'clue_eye',
    discovered: false,
    type: 'petroglyph',
    elevationFt: 3420,
    geology: 'Columnar Welded Dacite Tuff with Natural Weathering Window',
  },
  {
    id: 'tortilla_flat',
    name: 'Historic Town of Tortilla Flat & Salt River',
    shortDesc: 'USGS Elev. 1,780 ft. 1879 Apache Trail settlement and stagecoach camp on the south bank of Salt River Canyon.',
    position: { x: 0, y: 0, z: -252 },
    radius: 40,
    clueId: 'clue_tortilla_flat',
    discovered: true,
    type: 'town',
    elevationFt: 1780,
    geology: 'River Alluvial Terrace along Tortilla Creek & Salt River Canyon',
  },
  {
    id: 'malapais_mountain',
    name: 'Malapais Mountain Summit',
    gnisName: 'Malapais Mountain',
    shortDesc: 'USGS Elev. 4,229 ft. Dominant northern volcanic basalt massif historically known as "Black Mountain".',
    position: { x: 95, y: 0, z: -155 },
    radius: 36,
    clueId: 'clue_malapais',
    discovered: false,
    type: 'mountain',
    elevationFt: 4229,
    geology: 'Dark Basaltic Andesite & Weathered Volcanic Malpaís Caprock',
  },
  {
    id: 'black_top_mesa',
    name: 'Black Top Mesa',
    shortDesc: 'USGS Elev. 3,650 ft. Flat basalt tableland between Boulder & Needle Canyons, site of Spanish arrastras and petroglyphs.',
    position: { x: 35, y: 0, z: 75 },
    radius: 30,
    discovered: false,
    type: 'mesa',
    elevationFt: 3650,
    geology: 'Flat-Topped Basalt Mesa with Resistant Caprock',
  },
  {
    id: 'battleship_mountain',
    name: 'Battleship Mountain',
    shortDesc: 'USGS Elev. 3,240 ft. Knife-edge dacite keel and dramatic vertical prow rising above East Boulder Canyon.',
    position: { x: -85, y: 0, z: -80 },
    radius: 28,
    discovered: false,
    type: 'mountain',
    elevationFt: 3240,
    geology: 'Knife-Edge Dacite Keel & Sheer Symmetrical Prow',
  },
  {
    id: 'charlebois_spring',
    name: 'Charlebois Spring Oasis',
    shortDesc: 'USGS Elev. 2,480 ft. Historic perennial spring in La Barge Canyon shaded by giant Fremont cottonwoods. Vital water oasis.',
    position: { x: 65, y: 0, z: -75 },
    radius: 22,
    discovered: false,
    type: 'spring',
    elevationFt: 2480,
    geology: 'Alluvial Canyon Oasis & Perennial Bedrock Aquifer Seep',
  },
  {
    id: 'miners_needle',
    name: "Miners Needle",
    shortDesc: 'USGS Elev. 3,680 ft. Triple-crested volcanic dacite pinnacle with a natural eyelet aperture near Coffee Flat.',
    position: { x: 135, y: 0, z: 180 },
    radius: 26,
    discovered: false,
    type: 'spire',
    elevationFt: 3680,
    geology: 'Pinnacled Dacite Crags with Natural Eyelet Aperture',
  },
  {
    id: 'superstition_peak',
    name: 'Superstition Peak Summit',
    shortDesc: 'USGS Elev. 5,057 ft. The highest dominant summit in the Superstition Mountains, crowning the southern sheer caldera wall.',
    position: { x: -180, y: 0, z: 65 },
    radius: 40,
    discovered: false,
    type: 'mountain',
    elevationFt: 5057,
    geology: 'Welded Dacite Ash-Flow Tuff (Superstition Caldera, 20.5 Ma)',
  },
  {
    id: 'pistol_canyon',
    name: 'Pistol Canyon Box Gorge',
    shortDesc: 'USGS Elev. 2,620 ft. Rugged slot canyon where Dutch Hunter Roy Bradford lost his revolver in 1920 seeking the Dutchman mine.',
    position: { x: -46, y: 0, z: -130 },
    radius: 24,
    clueId: 'clue_pistol',
    discovered: false,
    type: 'canyon',
    elevationFt: 2620,
    geology: 'Steep Box Canyon with Conglomerate Boulder Chokes',
  },
  {
    id: 'lost_dutchman_mine',
    name: 'The Lost Dutchman Mine',
    shortDesc: 'USGS Elev. 3,180 ft. The legendary hidden gold mine masked by ironwood brush and fallen boulders.',
    position: { x: 160, y: 0, z: 110 },
    radius: 15,
    clueId: 'clue_mine',
    discovered: false,
    type: 'mine',
    elevationFt: 3180,
    geology: 'Hydrothermal Quartz Vein in Fault-Fractured Dacite Tuff',
  },
  {
    id: 'the_flatiron',
    name: 'The Flatiron Massif',
    gnisName: 'The Flatiron',
    shortDesc: 'USGS Elev. 4,861 ft. The immense western volcanic prow towering sheer over Siphon Draw, visible across the entire Salt River Valley.',
    position: { x: -420, y: 0, z: 90 },
    radius: 42,
    discovered: false,
    type: 'mountain',
    elevationFt: 4861,
    geology: 'Massive Welded Dacitic Ash-Flow Sheet with Vertical Jointing',
  },
  {
    id: 'hieroglyphic_spring',
    name: 'Hieroglyphic Spring & Canyon',
    gnisName: 'Hieroglyphic Spring',
    shortDesc: 'USGS Elev. 2,560 ft. Ancient Hohokam petroglyphs chiseled into dark basalt rimrock surrounding perennial tinajas bedrock pools.',
    position: { x: -360, y: 0, z: 280 },
    radius: 28,
    clueId: 'clue_petroglyph',
    discovered: false,
    type: 'spring',
    elevationFt: 2560,
    geology: 'Basalt Bedrock Pools (Tinajas) with Historic Petroglyph Panels',
  },
  {
    id: 'garden_valley',
    name: 'Garden Valley Plateau',
    gnisName: 'Garden Valley',
    shortDesc: 'USGS Elev. 2,240 ft. Expansive saguaro-blanketed mesa terrace between First and Second Water, prehistoric Agave roasting pits.',
    position: { x: -180, y: 0, z: -160 },
    radius: 35,
    discovered: false,
    type: 'mesa',
    elevationFt: 2240,
    geology: 'Broad Alluvial Desert Basin Terrace with Caliche Soil Horizons',
  },
  {
    id: 'reavis_ranch',
    name: 'Reavis Ranch Historic Homestead',
    gnisName: 'Reavis Ranch',
    shortDesc: 'USGS Elev. 3,840 ft. 1870s mountain homestead established by hermit Elisha Reavis along perennial Reavis Creek, heirloom apple orchards.',
    position: { x: 480, y: 0, z: -120 },
    radius: 32,
    discovered: false,
    type: 'camp',
    elevationFt: 3840,
    geology: 'Riparian Canyon Alluvium & Perennial Creek Drainage Oasis',
  },
  {
    id: 'canyon_lake',
    name: 'Canyon Lake & Mormon Flat',
    gnisName: 'Canyon Lake',
    shortDesc: 'USGS Elev. 1,660 ft. Dramatic turquoise canyon reservoir on the Salt River where the historic Apache Trail hugs sheer rhyolite walls.',
    position: { x: -120, y: 0, z: -450 },
    radius: 45,
    discovered: false,
    type: 'spring',
    elevationFt: 1660,
    geology: 'Salt River Gorge Fluvial Cut into Miocene Rhyolitic Ash Flow',
  },
];

export const INITIAL_CLUES: ClueItem[] = [
  {
    id: 'clue_trailhead',
    title: 'Trail Register & Peralta Map Fragment',
    lore: '"From my mine you can see the military road winding through the pass, but from the road you cannot see the mine."',
    hint: 'Head east toward the canyon spring to inspect ancient stone markings.',
    discovered: false,
    landmarkId: 'trailhead',
    iconName: 'Scroll',
    foundAt: 'Peralta Trailhead Camp',
  },
  {
    id: 'clue_petroglyph',
    title: 'Peralta Stone Tablet Symbols',
    lore: '"Follow the stream bed where the water sinks into the sand. Three crosses carved into volcanic tuff mark the trail south."',
    hint: 'Travel south toward the high red bluffs where old wooden crosses stand.',
    discovered: false,
    landmarkId: 'hieroglyphic_spring',
    iconName: 'Sparkles',
    foundAt: 'Hieroglyphic Oasis & Spring',
  },
  {
    id: 'clue_cross',
    title: 'Carved Wooden Cross Inscription',
    lore: '"A silver spur and a rusted stirrup beneath the scree. Jacob Waltz noted: The shadow of the great spire will stretch northeast across the canyon."',
    hint: "Head northeast to Waltz's old stone dugout and prospecting camp.",
    discovered: false,
    landmarkId: 'massacre_grounds',
    iconName: 'Compass',
    foundAt: '1848 Peralta Massacre Grounds',
  },
  {
    id: 'clue_dugout',
    title: "Waltz's Tattered Leather Journal",
    lore: '"Found the mother lode in a narrow cleft. Rose quartz with pure native gold ribboning through the basalt like honey. Masked the entrance with dead mesquite and heavy rocks."',
    hint: "Gaze toward Weaver's Needle. The needle casts a sharp shadow toward the eastern bluffs.",
    discovered: false,
    landmarkId: 'miners_ruins',
    iconName: 'BookOpen',
    foundAt: "Jacob Waltz's Abandoned Dugout",
  },
  {
    id: 'clue_needle',
    title: "Weaver's Needle Shadow Bearings",
    lore: '"At 4 o’clock in the afternoon, the shadow of Weaver\'s Needle points its apex directly at the Eye of the Mountain."',
    hint: 'Climb the ridge northeast to the high bluff with the natural stone window.',
    discovered: false,
    landmarkId: 'weavers_needle',
    iconName: 'Mountain',
    foundAt: "Weaver's Needle Lookout",
  },
  {
    id: 'clue_eye',
    title: 'The Aperture Sightline',
    lore: '"Looking through the natural eye of the rock when the sun sinks low, the golden ray strikes the entrance of the hidden mine shaft across the box canyon."',
    hint: 'Follow the sightline southeast into the secluded box canyon cleft at coords (+160, +110).',
    discovered: false,
    landmarkId: 'eye_ridge',
    iconName: 'Eye',
    foundAt: 'Eye of the Needle Bluff',
  },
  {
    id: 'clue_tortilla_flat',
    title: 'Tortilla Flat Saloon Ledger & Stage Records',
    lore: '"Stagecoach drivers along the Apache Trail recorded Jacob Waltz paying for salt pork, flour, and whiskey with coarse, wire-like gold nuggets that he claimed came from the three red peaks to the south."',
    hint: 'Refill your canteen at the wooden trough, warm up at the town campfire, and trade with the frontier provisioner.',
    discovered: true,
    landmarkId: 'tortilla_flat',
    iconName: 'Building2',
    foundAt: 'Historic Town of Tortilla Flat',
  },
  {
    id: 'clue_malapais',
    title: 'USGS Triangulation Benchmark & Summit Vista',
    lore: '"Malapais Mountain (elev. 4,229 ft) — From this dark basalt caprock, the apex of Weaver\'s Needle aligns true south with the Peralta Trail and the hidden gold-bearing quartz vein."',
    hint: 'Peer south toward Weaver\'s Needle through the surveyor transit, or follow the rocky drainage southwest down into Pistol Canyon.',
    discovered: false,
    landmarkId: 'malapais_mountain',
    iconName: 'Mountain',
    foundAt: 'Malapais Mountain Summit',
  },
  {
    id: 'clue_pistol',
    title: "Roy Bradford's Lost 1870s Colt Revolver & Journal",
    lore: '"Dutch Hunter Roy Bradford lost his Colt single-action revolver in this narrow box gorge while scrambling through boulder pour-offs in 1920. His journal notes: \'The canyon walls narrow to six paces; gold float traces in the gravel wash.\'"',
    hint: 'Follow the winding canyon wash north toward Peters Canyon or scramble up the pack trail west onto Peters Mesa.',
    discovered: false,
    landmarkId: 'pistol_canyon',
    iconName: 'Crosshair',
    foundAt: 'Pistol Canyon Box Gorge',
  },
  {
    id: 'clue_mine',
    title: 'The Lost Dutchman Cache & Shaft',
    lore: '"You have found it! The legendary entrance sealed with ironwood logs and heavy boulders. Beyond lies the vein of crystalline gold Waltz took to Phoenix!"',
    hint: 'Step inside the timbered drift to uncover the lost gold!',
    discovered: false,
    landmarkId: 'lost_dutchman_mine',
    iconName: 'Award',
    foundAt: 'The Lost Dutchman Mine',
  },
];
